import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * Lint config.
 *
 * Deliberately small. The type checker catches most of what a large rule set
 * would, and rules that fire constantly get disabled rather than followed.
 * These are the ones that catch real mistakes in this codebase.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**", "**/.next/**", "**/dist/**", "**/coverage/**",
      "**/playwright-report/**", "**/test-results/**", "**/.storage/**", "**/.mail/**",
      // Generated by Next on every build; not ours to lint.
      "**/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly", process: "readonly", Buffer: "readonly",
        fetch: "readonly", URL: "readonly", AbortSignal: "readonly",
        setTimeout: "readonly", clearTimeout: "readonly",
        window: "readonly", document: "readonly", navigator: "readonly",
        React: "readonly", HTMLElement: "readonly", FormData: "readonly",
        File: "readonly", Response: "readonly", Request: "readonly",
        Intl: "readonly", TextEncoder: "readonly", TextDecoder: "readonly",
      },
    },
    rules: {
      // Unused values are usually a leftover or a typo. `_` prefix opts out.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // `any` defeats the point of the strict config everywhere else.
      "@typescript-eslint/no-explicit-any": "error",
      // A floating promise in a server action silently drops the work.
      "no-console": ["warn", { allow: ["warn", "error", "log"] }],
      "prefer-const": "error",
      "no-var": "error",
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },
  {
    // Tests say what they mean; non-null assertions on fixtures are fine there.
    files: ["**/test/**/*.ts", "**/*.test.ts", "**/*.spec.ts"],
    rules: { "@typescript-eslint/no-non-null-assertion": "off" },
  },
);
